/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rutaalmacenes.gui;

import java.time.LocalTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import rutaalmacenes.logic.*;


/**
 *
 * @author CDJ
 */
public class FormCaminos extends javax.swing.JFrame {

    /**
     * Creates new form FormCaminos
     */
    private Grafo grafo;
    
    public FormCaminos(Grafo grafo) throws Exception {
        this.grafo=grafo;
        initComponents();
        aplicarFormatoGrid();
        
        aplicarFormatos();
        AyudaGUI.llenarComboBox(cbAlmacen,  grafo);
        
       updateGrid(tablaCaminos, grafo, (Almacen)cbAlmacen.getSelectedItem());
    }
    
    private void aplicarFormatos()
    {
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbAlmacen = new javax.swing.JComboBox();
        lbAlmacen = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCaminos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Caminos");

        cbAlmacen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbAlmacen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAlmacenItemStateChanged(evt);
            }
        });

        lbAlmacen.setText("Almacen");
        lbAlmacen.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbAlmacen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAlmacen)
                    .addComponent(cbAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tablaCaminos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "#", "Identificador", "Destino", "Duracion"
            }
        ));
        jScrollPane2.setViewportView(tablaCaminos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbAlmacenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAlmacenItemStateChanged
        try {
            // TODO add your handling code here:
            updateGrid(tablaCaminos, grafo, (Almacen)cbAlmacen.getSelectedItem());
        } catch (Exception ex) {
            Logger.getLogger(FormCaminos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbAlmacenItemStateChanged

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbAlmacen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAlmacen;
    private javax.swing.JTable tablaCaminos;
    // End of variables declaration//GEN-END:variables

public void updateGrid(javax.swing.JTable tabla, Grafo<Almacen> almacenes, Almacen almacen) throws Exception
    {
        DefaultTableModel model;
        model = (DefaultTableModel) tabla.getModel();
        model.setRowCount(0);
        ListaSE<NodoAP> adyacentes=almacenes.VerticesAdyacentes(almacen);
       
        for (int i = 0; i < adyacentes.Longitud(); i++) {
            updateGridLine(almacenes, adyacentes,model,i );
        }
    }
   
    private void updateGridLine(Grafo<Almacen> almacenes, ListaSE<NodoAP> caminos, DefaultTableModel model, int i ) throws Exception
    {
        Almacen almacen;
       
        if (caminos!=null)
        {
            almacen=almacenes.getLista().Obtener(caminos.Obtener(i).getAdyacenciaNodo());
           
            String id=almacen.getID();
            String destino=almacen.getCiudad();
            LocalTime tiempoRecorrido = caminos.Obtener(i).getTiempoRecorrido();
            model.addRow(new Object[]{i+1, id, destino, tiempoRecorrido});
        }
    }
    
    private void aplicarFormatoGrid()
    {
        // se reduce y se el tamano del ancho de la columna a 30 bajo la 
        // suposicion que no nunca se excederan los numero de 3 digitos 
        javax.swing.table.TableColumn columnaNumero = tablaCaminos.getColumnModel().getColumn(0);
        columnaNumero.setMaxWidth(30);
        columnaNumero.setMinWidth(30);
    }
}
