/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rutaalmacenes.gui;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import rutaalmacenes.logic.*;

/**
 *
 * @author Seelee
 */
public class FormEliminarCamino extends javax.swing.JFrame {

    /**
     * Creates new form AislarEdificio
     */
    Grafo grafo;
    public FormEliminarCamino(Grafo grafo) throws Exception {
        this.grafo=grafo;
        initComponents();
        aplicarFormatos();
        FormAgregarCaminos.llenarComboBoxesForm(cbAlmacenInicio, cbAlmacenDestino, grafo);

    }
    
    private void aplicarFormatos()
    {
        setLocationRelativeTo(null);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbAlmacenInicio = new javax.swing.JComboBox();
        btnInicio = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cbAlmacenDestino = new javax.swing.JComboBox();
        btnDestino = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eliminar Camino");

        cbAlmacenInicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbAlmacenInicio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAlmacenInicioItemStateChanged(evt);
            }
        });

        btnInicio.setText("Inicio");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        cbAlmacenDestino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbAlmacenDestino.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAlmacenDestinoItemStateChanged(evt);
            }
        });

        btnDestino.setText("Destino");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnInicio)
                        .addGap(18, 18, 18)
                        .addComponent(cbAlmacenInicio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDestino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbAlmacenDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 287, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAlmacenInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAlmacenDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDestino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbAlmacenInicioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAlmacenInicioItemStateChanged
        // TODO add your handling code here:
       // validarSalvar();
    
    }//GEN-LAST:event_cbAlmacenInicioItemStateChanged

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    
        if (validarEliminarCamino(grafo, cbAlmacenInicio.getSelectedItem() , cbAlmacenDestino.getSelectedItem())) {
            try {
                grafo.EliminarArco((Vertice)cbAlmacenInicio.getSelectedItem(),(Vertice)cbAlmacenDestino.getSelectedItem());
                JOptionPane.showMessageDialog(rootPane, "No Existe el Camino");
                dispose();
            } catch (Exception ex) {
                Logger.getLogger(FormEliminarCamino.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cbAlmacenDestinoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAlmacenDestinoItemStateChanged
        // TODO add your handling code here:
        //validarSalvar();
    }//GEN-LAST:event_cbAlmacenDestinoItemStateChanged
    

    private boolean validarEliminarCamino(Grafo grafo, Object a1, Object a2)
    {
        try {
            if (!grafo.EstaElArco((Almacen)a1, (Almacen)a2)) {
                JOptionPane.showMessageDialog(rootPane, "No Existe el Camino");
                return false; 
            }
            
        } catch (Exception ex) {
      
            Logger.getLogger(FormAgregarCaminos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (a1.equals(a2)) {
            JOptionPane.showMessageDialog(rootPane, "No puede eliminar sobre el mismo vertice");
            return false; 
        }

        return true;
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel btnDestino;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel btnInicio;
    private javax.swing.JComboBox cbAlmacenDestino;
    private javax.swing.JComboBox cbAlmacenInicio;
    // End of variables declaration//GEN-END:variables
}
